# Generated by Django 3.2.7 on 2021-12-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('is_read', '-created_time'), 'verbose_name_plural': 'Tin nhắn'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Hồ sơ cá nhân'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name_plural': 'Kỹ năng'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
