# Generated by Django 3.2.7 on 2021-12-15 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-created_time',)},
        ),
    ]
