# Generated by Django 3.2.7 on 2021-12-15 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20211215_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-created_time',), 'verbose_name_plural': 'Dự án'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': 'Đánh giá'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'Thẻ'},
        ),
    ]
