# Generated by Django 3.2.7 on 2021-12-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20211216_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('up', 'Tích cực'), ('down', 'Tiêu cực')], max_length=200),
        ),
    ]
