# Generated by Django 3.2.7 on 2021-12-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vai trò'),
        ),
    ]
